language: node_js

node_js:
- node

before_install:
  - chmod +x ./deploy/frontend.sh  
  - chmod +x ./deploy/functions.sh
  - pip install --user awscli
  
jobs:
  include:
    - stage: deploy_frontend
      script: ./deploy/frontend.sh
      after_succes:
        - pwd
        - ls
        - aws s3 sync dist s3://cod-omc-sellison/cod-omc
    - stage: deploy_functions
      script: ./deploy/functions.sh